options:
  porta: 3000
  mensagem: "Ol√° do Add-on Node!"
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_user: "mqtt_addon"
  mqtt_password: ""

schema:
  porta: int
  mensagem: str
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password