---
name: Terrasmart
slug: terrasmart_node_mqtt
version: 1.1.0
description: Agente local para integração com dispositivos
url: https://github.com/lerototi/terrasmart
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
host_network: true
ingress: false

build:
  dockerfile: Dockerfile

options:
  log_level: info
  porta: 8080
  mqtt_host: "localhost"
  mqtt_port: 1883
  mqtt_user: "mqtt_addon"
  mqtt_password: "1234"

schema:
  log_level: list(trace|debug|info|warning|error)
  porta: int
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password

ports:
  8080/tcp: 8080

panel_icon: mdi:nodejs